networks:
  frontend:
  testing:

services:

  server:
    build:
      context: .
      target: server
      args: &buildargs
        ENVIRONMENT: ${ENVIRONMENT}
        WORKDIR: ${WORKDIR}
        DEBUGGER_DEBUGPY: ${DEBUGGER_DEBUGPY}
        UID: ${UID}
        GID: ${GID}
    user: ${UID}:${GID}
    entrypoint: docker-entrypoint.sh
    command: pserve ${ENVIRONMENT}.ini --reload
    profiles:
      - production
      - staging
      - development
    networks:
      - frontend
    ports:
      - "${DOCKER_PORTMAP_IP}:${DOCKER_PORTMAP_PORT_SERVER}:6543"
      - "${DOCKER_PORTMAP_IP}:5253:5253"  # for debugging
    volumes:
      - .:/code
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      SELENIUM_GRID_URL: ${SELENIUM_GRID_URL}
      SELENIUM_SCREENSHOTS: ${SELENIUM_SCREENSHOTS}
      MEMBERSHIP_URL: ${MEMBERSHIP_URL}
      MEMBERSHIP_MAIL_HOST: ${MEMBERSHIP_MAIL_HOST}
      MEMBERSHIP_MAIL_PORT: ${MEMBERSHIP_MAIL_PORT}
      MEMBERSHIP_MAIL_TO_CONSOLE: ${MEMBERSHIP_MAIL_TO_CONSOLE}
      MEMBERSHIP_STATUS_RECEIVER: ${MEMBERSHIP_STATUS_RECEIVER}
      MEMBERSHIP_STATUS_RECEIVER_GPGID: ${MEMBERSHIP_STATUS_RECEIVER_GPGID}
      MEMBERSHIP_DEFAULT_SENDER: ${MEMBERSHIP_DEFAULT_SENDER}
      MEMBERSHIP_NOTIFICATION_SENDER: ${MEMBERSHIP_NOTIFICATION_SENDER}
      MEMBERSHIP_CERTIFICATE_TEMPLATE: ${MEMBERSHIP_CERTIFICATE_TEMPLATE}
      MEMBERSHIP_API_AUTH_TOKEN: ${MEMBERSHIP_API_AUTH_TOKEN}
      MEMBERSHIP_TICKETING_URL: ${MEMBERSHIP_TICKETING_URL}
      MEMBERSHIP_DEBUG_AUTHORIZATION: ${MEMBERSHIP_DEBUG_AUTHORIZATION}
      MEMBERSHIP_DEBUG_NOTFOUND: ${MEMBERSHIP_DEBUG_NOTFOUND}
      MEMBERSHIP_DEBUG_ROUTEMATCH: ${MEMBERSHIP_DEBUG_ROUTEMATCH}
      MEMBERSHIP_DEBUG_TEMPLATES: ${MEMBERSHIP_DEBUG_TEMPLATES}

  mail:
    image: axllent/mailpit
    profiles:
      - development
    networks:
      - frontend
    ports:
      - "${DOCKER_PORTMAP_IP}:${DOCKER_PORTMAP_PORT_MAILHOG}:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    # logging:
    #   driver: none

  tests:
    build:
      context: .
      target: server
      args: *buildargs
    user: ${UID}:${GID}
    entrypoint: docker-entrypoint.sh
    command: ./test.sh
    profiles:
      - testing
    depends_on:
      - browser
    networks:
      - testing
    volumes:
      - .:/code
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      TESTING: 1
      SELENIUM_GRID_URL: ${SELENIUM_GRID_URL}
      SELENIUM_SCREENSHOTS: ${SELENIUM_SCREENSHOTS}

  browser:
    image: selenium/standalone-chrome:4.47.0
    profiles:
      - testing
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - testing

  documentation:
    build:
      context: .
      target: documentation
      args: *buildargs
    user: ${UID}:${GID}
    entrypoint: docker-entrypoint.sh
    command: bash -c "cd docs; make html"
    profiles:
      - documentation
    volumes:
      - .:/code
    environment:
      ENVIRONMENT: ${ENVIRONMENT}

