[pytest]

# filterwarnings = action:message:category:module:line
filterwarnings =
    ignore:'cgi':DeprecationWarning
    ignore:find_module():DeprecationWarning
    ignore:FileFinder.find_loader():DeprecationWarning
    ignore:Authentication and authorization policies have been deprecated:DeprecationWarning
    ignore:The new security policy has deprecated unauthenticated_userid:DeprecationWarning
    ignore:The behavior of (AcceptLanguageValidHeader)?.best_match:DeprecationWarning
    ignore::sqlalchemy.exc.MovedIn20Warning
