[app:main]
use = egg:c3sMembership

pyramid.reload_templates = false
pyramid.debug_authorization = ${MEMBERSHIP_DEBUG_AUTHORIZATION}
pyramid.debug_notfound = ${MEMBERSHIP_DEBUG_NOTFOUND}
pyramid.debug_routematch = ${MEMBERSHIP_DEBUG_ROUTEMATCH}
pyramid.debug_templates = ${MEMBERSHIP_DEBUG_TEMPLATES}
pyramid.default_locale_name = en
pyramid.includes = pyramid_tm

sqlalchemy.url = sqlite:///%(here)s/c3sMembership.db



##############################
# settings for c3sMembership #
##############################

c3smembership.runmode = prod

# The notification sender email address is used for sending emails like the
# email address confirmation link, the membership certificate and dues
# invoices.
c3smembership.notification_sender = ${MEMBERSHIP_NOTIFICATION_SENDER}

# The status receiver email address is used as a recipient for status emails
# send by the membership application like the new application email which
# informs the staff that a new application was submitted.
c3smembership.status_receiver = ${MEMBERSHIP_STATUS_RECEIVER}
c3smembership.status_receiver_gpgid = ${MEMBERSHIP_STATUS_RECEIVER_GPGID}

c3smembership.dashboard_number = 20
c3smembership.adminpass = rut
c3smembership.adminlogin = berries
c3smembership.url = ${MEMBERSHIP_URL}
c3smembership.certificate_template = ${MEMBERSHIP_CERTIFICATE_TEMPLATE}

mail.host = ${MEMBERSHIP_MAIL_HOST}
mail.port = ${MEMBERSHIP_MAIL_PORT}
mail.default_sender = ${MEMBERSHIP_DEFAULT_SENDER}

available_languages = de en

api_auth_token = ${MEMBERSHIP_API_AUTH_TOKEN}
ticketing.url = ${MEMBERSHIP_TICKETING_URL}

testing.mail_to_console = ${MEMBERSHIP_MAIL_TO_CONSOLE}


[server:main]
use = egg:waitress#main
host = 0.0.0.0
port = 6543


###########
# Logging #
###########

[loggers]
keys = root, c3smembership, sqlalchemy, accounting

[handlers]
keys = console, filelog

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console

[logger_c3smembership]
level = WARN
handlers =
qualname = c3smembership

[logger_accounting]
level = DEBUG
handlers =
qualname = c3smembership.acc

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine
# "level = INFO" logs SQL queries.
# "level = DEBUG" logs SQL queries and results.
# "level = WARN" logs neither.  (Recommended for production systems.)

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[handler_filelog]
class = FileHandler
args = ('%(here)s/yes.debug.log','a')
level = DEBUG
formatter = generic

[formatter_generic]
format = %(asctime)s %(levelname)-5.5s [%(name)s][%(threadName)s] %(message)s
